### ISSUE TITLE
Metadata update

### ISSUE THREAD

**Issue by reeshmabijosh** [yoursshahnawaz/COVID19-India#3]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/SXOXJZ

Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by yoursshahnawaz** [comment]
Thank you.
I would love to help.

**Comment by k-goncharova** [comment]
Thank you for your response and willingness to contribute. Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the necessary permissions for editing your dataset. You could proceed with adding metadata (descriptions, keywords) then.

**Comment by yoursshahnawaz** [comment]
I've successfully registered.

**Comment by k-goncharova** [comment]
Great. I've just given you the necessary permissions. Feel free to contact me, if you might need any help with the update.

**Comment by k-goncharova** [comment]
Hello @yoursshahnawaz, I just wanted to check if you might need any help. I see the draft version of your updated dataset in Dataverse. Do you have any questions on metadata or on the process of publishing updates?

**Comment by yoursshahnawaz** [comment]
Earlier I had few troubles updating the data and then about the process to be followed. But gradually, I'm getting along with it. 
I've submitted the data for review.
